---
.gitlab-ci.yml:
  unmanaged: true

.travis.yml:
  docker_sets:
    - set: docker/centos-7
    - set: docker/ubuntu-14.04
  docker_defaults:
    bundler_args: ""
  secure: ""
  branches:
    - release
  global_env:
    - GEM_BOLT=true
  remove_includes:
    - env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.4

.yardopts:
  optional:
    - --output-dir docs/

Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw
      - gem: bolt
        version: '~> 1.3'
        condition: ENV['GEM_BOLT']

Rakefile:
  requires:
    - puppet-lint/tasks/puppet-lint
  extras: |
    # spec_prep is required to setup fixtures used by the acceptance tests
    beaker_task = Rake::Task['beaker']
    spec_prep =  Rake::Task['spec_prep']
    beaker_task.enhance(beaker_task.prerequisite_tasks << spec_prep)

spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
